### ISSUE TITLE
Support labels

### ISSUE THREAD

**Issue by miphe** [mytalengi/myt-pie-chart#13]
Right now the label used in the pie chart is the `data.name` attribute. I would like to support a separate label, which would default (if omitted) to the `data.name` attribute.

The data model may look like this:

``` javascript
name: 'phtm',
label: 'The Phantom',
value: 1589,
bgColor: '#ccc',
color: '#444'
```

or like this:

``` javascript
name: 'phtm',
value: 1589,
bgColor: '#ccc',
color: '#444'
```

In the last example, the label used in the graph would default to `phtm`.

**Comment by anteAdamovic** [comment]
Just a note on implications with C3 line chart, it uses 'name' attribute as 'label' and can't be changed so if we want to avoid breaking things we will have to use 'label' for line charts also. Will explain in detail once I make the required changes.
